In [2]:
import numpy as np
a=np.array([10,20,30,40,50])
print("One dimensional array:",a)

One dimensional array: [10 20 30 40 50]


In [4]:
import numpy as np
b=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("Two dimensional array:",b)

Two dimensional array: [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [5]:
import numpy as np
c=np.zeros((3,5))
print("\n Array with all zeros:\n",c)


 Array with all zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
import numpy as np
d=np.random.random((3,3))
print("\n Random value:\n",d)


 Random value:
 [[0.35507195 0.81209456 0.8294121 ]
 [0.77540669 0.63444027 0.34330152]
 [0.32895178 0.86875831 0.01788786]]


In [8]:
import numpy  as np
e=np.arange(0,100,5)
print("\n Range value:\n",e)


 Range value:
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [9]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarr=arr.reshape((4,3))
print("\n Original array:\n",arr)
print("\n Reshaped array [4,3]:\n", newarr)


 Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 Reshaped array [4,3]:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [2]:
import numpy as np
arr0=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
arr=np.zeros((5,3))
arr2=np.random.random((5,3))
arr3=np.arange(0,10,1)
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
arr4=a.reshape((3,5))
flat=arr0.flatten()
print('\n shape of array:',arr0.shape)
print('\n no of dimensions:\n',a.ndim)
print('\n array :\n',arr0)
print('\n zero array:\n',arr)
print('\n random array:\n',arr2)
print('\n step size:\n',arr3)
print('\n original array:\n',a)
print('\n reshaped array:\n',arr4)
print('flattened array:\n',flat)


 shape of array: (5, 3)

 no of dimensions:
 2

 array :
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

 zero array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 random array:
 [[0.06157614 0.95984951 0.73487053]
 [0.7337365  0.84303301 0.85073603]
 [0.66250827 0.60367998 0.678265  ]
 [0.05787387 0.89700726 0.02309712]
 [0.79169284 0.8236466  0.6199295 ]]

 step size:
 [0 1 2 3 4 5 6 7 8 9]

 original array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

 reshaped array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
flattened array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [6]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("\n array element type:\n",arr.dtype)



 array element type:
 int32


In [7]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newtype=arr.astype('f')
print("\n convert array element:\n",newtype)
print('\n converted array:\n',newtype.dtype)


 convert array element:
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]

 converted array:
 float32


In [8]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
length=len(arr)
print('\n length of array: \n',length)



 length of array: 
 3


In [9]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('\n length of array: \n',arr.size)



 length of array: 
 12
